# Generated by Django 5.1.6 on 2025-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='leavingDate',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
